### ISSUE TITLE
Good tiles, better engine searcher? 

### ISSUE THREAD

**Issue by yopaseopor** [floledermann/mapzr.com#12]
What a good resolution of your tiles, it works very well, but... there si something you can modify/add to your map to make it better. How about a new searcher in OSM database?

How about:
1-possibility of searching three fields to search nodes, ways and specific relations
2-possibility of searching keys via iD predictives presets translations or something like that.
3-possibility of searching by well-defined zones in OSM data-base, like OSMCha does.
4- Predictive search for all the items in the map

**Comment by floledermann** [comment]
Probably not gonna happen. While search could be improved, this should be a tool for end-users which are not necessarily familiar with OSM internals.
